### PR TITLE
LPS-119917 use the new util classes to avoid duplicated code

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-119917

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [natocesarrego#810](https://github.com/natocesarrego/liferay-portal/pull/810).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#220](https://github.com/carolmariaabb/liferay-portal/pull/220).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
ci:stop

**Pull request closed without merging**
