### PR TITLE
LPS-132621 | LPS-133378 Remove Hide Field and Input Mask feature flags

### PR DESCRIPTION
**Pull request by brunofariasdeo**
Related Issues: 
Input Mask: https://issues.liferay.com/browse/LPS-132621
Hide Field: https://issues.liferay.com/browse/LPS-133378

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by brunofariasdeo** [comment]
ci:test:sf

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @brunofariasdeo, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @brunofariasdeo, can you please check if these failures are related to your changes? Thanks

**Comment by brunofariasdeo** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
