### PR TITLE
LPS-1166590 make the necessary changes to guarantee that project template generate works on 7.3 properly

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-116590

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [natocesarrego#666](https://github.com/natocesarrego/liferay-portal/pull/666).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#162](https://github.com/carolmariaabb/liferay-portal/pull/162).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
