### PR TITLE
LPS-135424 | LPS-135496 | LPS-135543

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issues:
https://issues.liferay.com/browse/LPS-135543
https://issues.liferay.com/browse/LPS-135424
https://issues.liferay.com/browse/LPS-135496

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
