### PR TITLE
LPS-116225 create test for color list

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-116225

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request forwarded to https://github.com/natocesarrego/liferay-portal/pull/637.<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#152](https://github.com/carolmariaabb/liferay-portal/pull/152).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
