### PR TITLE
LPS-118317 create unit test for the formatBigDecimal method

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-118317

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Pull request forwarded to https://github.com/natocesarrego/liferay-portal/pull/734.<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#192](https://github.com/carolmariaabb/liferay-portal/pull/192).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
