### PR TITLE
LPS-121831 baseline

### PR DESCRIPTION
**Pull request by marcosapmf**
Related Issue: https://issues.liferay.com/browse/LPS-121831

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
Hey @marcosapmf, can you please fix the source formatter issues and resend? Thanks

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [carolmariaabb#238](https://github.com/carolmariaabb/liferay-portal/pull/238).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#237](https://github.com/carolmariaabb/liferay-portal/pull/237).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
