### PR TITLE
LPS-118607 create a integration test for updating report when form has nested fields

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-118607

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Pull request forwarded to https://github.com/natocesarrego/liferay-portal/pull/743. [See changes here.](https://github.com/carolmariaabb/liferay-portal/compare/922b2a0b3c10~3...922b2a0b3c10)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#197](https://github.com/carolmariaabb/liferay-portal/pull/197).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
