### PR TITLE
LPS-123483

### PR DESCRIPTION
**Pull request by brianchandotcom**
Related Issue: https://issues.liferay.com/browse/LPS-123483

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/96342

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by liferay-forms** [comment]
Hey @brianchandotcom, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [carolmariaabb#268](https://github.com/carolmariaabb/liferay-portal/pull/268).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#267](https://github.com/carolmariaabb/liferay-portal/pull/267).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
