### PR TITLE
LPS-109804 register the new upgrade step

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-109804

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [natocesarrego#691](https://github.com/natocesarrego/liferay-portal/pull/691).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#174](https://github.com/carolmariaabb/liferay-portal/pull/174).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
