### PR TITLE
LPS-119404 build lang

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-119404

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [natocesarrego#815](https://github.com/natocesarrego/liferay-portal/pull/815).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#222](https://github.com/carolmariaabb/liferay-portal/pull/222).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
