### PR TITLE
LPS-115938 update test snapshot

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-115938

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [carolmariaabb#155](https://github.com/carolmariaabb/liferay-portal/pull/155).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#154](https://github.com/carolmariaabb/liferay-portal/pull/154).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
