### PR TITLE
LPS-140084 It is not possible to add special characters on a String type field that has a Field Name called name

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-140084

- LPS-140084 Define properties instead of using the fieldName
- LPS-140084 Fix tests
- LPS-140084 Increment tests

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
