### PR TITLE
LPS-117783 start workflow instance when update transaction finish to avoid org.hibernate.StaleObjectStateException

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-117783

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
@marcosapmf eu rodei esses dois testes localmente e eles falharam (`DDMFormInstanceRecordUADAnonymizerTest.testAutoAnonymize` e `DDMFormInstanceRecordStagedModelDataHandlerTest.testVersionMatchingAfterExportImport`). Tu poderia dar uma olhada?

**Comment by marcosapmf** [comment]
> @marcosapmf eu rodei esses dois testes localmente e eles falharam (`DDMFormInstanceRecordUADAnonymizerTest.testAutoAnonymize` e `DDMFormInstanceRecordStagedModelDataHandlerTest.testVersionMatchingAfterExportImport`). Tu poderia dar uma olhada?

Posso sim @carolmariaabb, valeu :)

**Pull request closed without merging**
