### PR TITLE
 LPS-135424 | LPS-135496

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issues: 
https://issues.liferay.com/browse/LPS-135424
https://issues.liferay.com/browse/LPS-135496

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please fix the source formatter issues and resend? Thanks

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please fix the source formatter issues and resend? Thanks

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:stop

**Pull request closed without merging**
