### PR TITLE
LPS-135713 Predefined Value must come first in case the field is being edited in the Form Builder. In User View, the predefinedValue is always empty

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-135713

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by liferay-forms** [comment]
ci:test:relevant

**Pull request closed without merging**
