### PR TITLE
LPS-115938 hide management toolbar and translation manager while syncActiveNavItem does not run

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-115938

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:forms

**Pull request closed without merging**
