### PR TITLE
LPS-116779 test upgrade

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-116779

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [natocesarrego#686](https://github.com/natocesarrego/liferay-portal/pull/686).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#173](https://github.com/carolmariaabb/liferay-portal/pull/173).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
