### PR TITLE
LPS-115417 call upgrade

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-115417

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [natocesarrego#672](https://github.com/natocesarrego/liferay-portal/pull/672).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#166](https://github.com/carolmariaabb/liferay-portal/pull/166).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
