### PR TITLE
LPS-127063 Add a margin between management and translation bar

### PR DESCRIPTION
**Pull request by brunofariasdeo**
Related Issue: https://issues.liferay.com/browse/LPS-127063

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Great job @brunofariasdeo 🎉👏🏽 
I made some small changes and also took the opportunity to add a unit test.
Please se the changes [here](https://github.com/carolmariaabb/liferay-portal/pull/299). 

Thanks!

**Pull request closed without merging**
