### PR TITLE
LPS-117467 implement front end tests to test the option name new behavior

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-117467

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [carolmariaabb#190](https://github.com/carolmariaabb/liferay-portal/pull/190).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#188](https://github.com/carolmariaabb/liferay-portal/pull/188).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
