### PR TITLE
LPS-113023 test fix

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-113023

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [natocesarrego#651](https://github.com/natocesarrego/liferay-portal/pull/651).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#160](https://github.com/carolmariaabb/liferay-portal/pull/160).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
