### PR TITLE
LPS-118759 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-118759

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [natocesarrego#770](https://github.com/natocesarrego/liferay-portal/pull/770).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#208](https://github.com/carolmariaabb/liferay-portal/pull/208).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
