### PR TITLE
LPS-117498 sort rows and columns by index

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-117498

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
@marcosapmf falhou um teste de front `MultiBarChart.es.js:54:32`

**Comment by marcosapmf** [comment]
> @marcosapmf falhou um teste de front `MultiBarChart.es.js:54:32`

Certo, @carolmariaabb. vou dar uma olhada :D

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Pull request submitted to [natocesarrego#696](https://github.com/natocesarrego/liferay-portal/pull/696).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#175](https://github.com/carolmariaabb/liferay-portal/pull/175).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
