### PR TITLE
LPS-79499 re-render Switch component when initial value changes

### PR DESCRIPTION
**Pull request by marcosapmf**
Related Issue: https://issues.liferay.com/browse/LPS-79499

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
Hey @marcosapmf, can you please fix the source formatter issues and resend? Thanks

**Comment by carolmariaabb** [comment]
ci:open

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
