### PR TITLE
LPS-138737 | LPS-138738

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issues: 
https://issues.liferay.com/browse/LPS-138737
https://issues.liferay.com/browse/LPS-138738

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1297401_257

**Comment by carolmariaabb** [comment]
ci:reevaluate:1297401_257

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by carolmariaabb** [comment]
ci:reevaluate:1237401_7977

**Comment by carolmariaabb** [comment]
ci:reevaluate:1237401_7977

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
> Previous `ci:test:relevant`[build](https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/7977) was unsuccessfully [reevaluated](https://test-1-31.liferay.com/job/test-portal-evaluate-pullrequest/16/) against more recent upstream results.
> 
> ### ❌ ci:test:stable - 9 out of 10 jobs passed
> ### ❌ ci:test:relevant - 18 out of 23 jobs passed in 4 hours 14 minutes
> Click here for more details.

**Pull request closed without merging**
