### PR TITLE
LPS-115938 change prevent href approach

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-115938

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Pull request submitted to [alinedoleron#154](https://github.com/alinedoleron/liferay-portal/pull/154).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carolmariaabb** [comment]
Closed [#153](https://github.com/carolmariaabb/liferay-portal/pull/153).<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
